[package]
name = "monistode-cli"
version = "0.1.4"
edition = "2021"
description = "The CLI interface for the monistode binutils."
license = "MIT"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
monistode-binutils = "0.1.3"
monistode-assemblers = "0.1.6"
